services:
  - type: web
    name: cms-setting-auto
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
